### ISSUE TITLE
Seperation of Wireframe and IO

### ISSUE THREAD

**Issue by multiholle** [JeanLebrument/iOSModuleArchitecture#2]
Why are you separating the Wireframe and the IO interface of a module? Isn't by design of the VIPER architecture the Wireframe responsible for the navigation between modules?

**Comment by JeanLebrument** [comment]
Thanks for your question.

If we stick to the separation of concerns, where a class has a single purpose and a single reason to change, it makes more sense that the wireframe manages only the displaying of the view inside the window (modal, etc.) and the IO class manages the navigation between modules.

**Comment by ciwong1** [comment]
bonjour, JeanLebrument,
we highly appreciate your project of iOSModuleArchitecture, ciwong is an advanced internet comprehensive service provider which focuses on the areas of primary and secondary schools. we are looking for an ios architect, I wonder if you are interested in, and look forward to your replay.

**Comment by JeanLebrument** [comment]
Thanks for your message! Definetly I would like to have more informations about this opportunity and your company. You can email me at jean.lebrument@gmail.com I'm looking forward to hearing from you.
