### ISSUE TITLE
[Question] regarding FirstModuleIO.swift

### ISSUE THREAD

**Issue by shaneowens** [JeanLebrument/iOSModuleArchitecture#3]
Hi, Thanks very much for providing this example architecture, it has helped 
me a lot.

I was wondering if you could explain why within `launchModule` in [FirstModuleIO.swift](https://github.com/JeanLebrument/iOSModulesArchitecture/blob/master/iOSModuleArchitecture/Code/Modules/FirstModule/IO/FirstModuleIO.swift)

**i.e.**

```
extension FirstModuleIO: IFirstModuleInput
{
    func launchModule(window: UIWindow)
    {
        wireframe?.presentInterfaceFromWindow(UIApplication.sharedApplication().windows[0] as! UIWindow)

        wireframe?.viewController?.eventHandler = presenter
        presenter?.userInterface = wireframe?.viewController
    }
}
```

do the lines 

```
wireframe?.viewController?.eventHandler = presenter
presenter?.userInterface = wireframe?.viewController
```

come **after** the line

`wireframe?.presentInterfaceFromWindow(UIApplication.sharedApplication().windows[0] as! UIWindow)`

and not **before**?

Many Thanks,
Shane

**Comment by JeanLebrument** [comment]
Hello,

Actually you're right, this is cleaner to do this before. But the execution is fast enough to not cause bug.
